import { stripQuotedAndPastedContent } from "./quote-detection.js";
import type { PriorErrorContext } from "./prior-error-context.js";

export type PriorErrorEvaluation =
  | { status: "violated"; stopBlock: string; reason: string }
  | { status: "satisfied"; reason: string; fullPass?: boolean }
  | { status: "defer" };

interface PriorErrorProfile {
  requiredTerms: RegExp[];
  forbiddenTerms: RegExp[];
  bannedActionPatterns: RegExp[];
  satisfactionPatterns: RegExp[];
  fullPassAllowed: boolean;
}

const PLANFILE_REMEDIATION_STOP_BLOCK =
  `[AUTOGENERATED STOP HOOK FEEDBACK]\nYou refused the required planfile validation remediation. Edit the named planfile directly, run validate_plan for that same path until it passes, then present the validated file as a whole-message <proposed_plan>...</proposed_plan> block. Do not ask to leave Plan Mode, do not call a different command, do not argue about Plan Mode writes, and do not emit another inline-only plan.`;

const WORD_BOUNDARY_CHARS = String.raw`[A-Za-z0-9_/-]`;

function literalTerm(term: string): RegExp {
  const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/g, String.raw`\s+`);
  return new RegExp(`(?<!${WORD_BOUNDARY_CHARS})${escaped}(?!${WORD_BOUNDARY_CHARS})`, "i");
}

function normalize(text: string): string {
  return text.toLowerCase().replace(/\s+/g, " ").trim();
}

function hasPattern(text: string, patterns: readonly RegExp[]): boolean {
  return patterns.some((pattern) => pattern.test(text));
}

function planfileProfile(contextText: string): PriorErrorProfile | null {
  if (
    !/\b(?:plan validation failed|iterate on the planfile|validate_plan|planfile edits are explicitly allowed|required planfile validation remediation)\b/i.test(contextText)
  ) {
    return null;
  }

  return {
    requiredTerms: [
      /\bplanfile\b/i,
      /\bvalidate_plan\b/i,
      /<proposed_plan>[\s\S]*<\/proposed_plan>|proposed_plan/i,
    ],
    forbiddenTerms: [
      /\b(?:do not|don't)\s+ask\s+to\s+(?:leave|exit)\s+plan mode\b/i,
      /\b(?:do not|don't)\s+call\s+a\s+different\s+command\b/i,
      /\b(?:do not|don't)\s+argue\s+about\s+plan mode writes\b/i,
      /\b(?:do not|don't)\s+emit\s+another\s+inline-only\s+plan\b/i,
    ],
    bannedActionPatterns: [
      /\b(?:exit|leave)\s+plan mode\b[\s\S]{0,220}\b(?:then|so|before)\b[\s\S]{0,220}\b(?:edit|update|write|modify|patch|revise)\b/i,
      /\bhigher-priority\b[\s\S]{0,240}\b(?:plan mode|write restrictions?|file writes?|mutating actions?)\b/i,
      /\b(?:cannot|can't|unable to|blocked|forbids?|forbidden|not allowed)\b[\s\S]{0,180}\b(?:edit|update|write|modify|patch|revise)\b[\s\S]{0,160}\bplanfile\b/i,
      /\b(?:plan mode|write restrictions?|file writes?|mutating actions?)\b[\s\S]{0,180}\b(?:cannot|can't|unable|blocked|forbids?|forbidden|not allowed)\b/i,
      /\b(?:higher-level|higher level|governing|current|active)\b[\s\S]{0,120}\binstructions?\b[\s\S]{0,180}\b(?:prevent|prevents|forbids?|forbidden|blocks?|blocked|disallows?)\b[\s\S]{0,180}\b(?:file writes?|mutating files?|mutation|edit(?:ing)?|writ(?:e|ing)|planfile)\b/i,
      /\b(?:file writes?|mutating files?|mutation|edit(?:ing)?|writ(?:e|ing)|planfile)\b[\s\S]{0,180}\b(?:prevented|forbidden|blocked|disallowed)\b[\s\S]{0,180}\b(?:higher-level|higher level|governing|current|active)\b[\s\S]{0,120}\binstructions?\b/i,
      /\b(?:provide|emit|write|show)\b[\s\S]{0,160}\b(?:inline|replacement content|patch)\b[\s\S]{0,160}\b(?:instead|but|rather than|cannot apply)\b/i,
    ],
    satisfactionPatterns: [
      /\b(?:i(?:'ll| will)|i(?:'m| am)\s+(?:going|about)|let me|now i(?:'ll| will))\b[\s\S]{0,220}\b(?:edit|update|modify|write|patch|revise)\b[\s\S]{0,160}\bplanfile\b[\s\S]{0,260}\bvalidate_plan\b/i,
      /\b(?:edited|updated|modified|patched|revised|wrote)\b[\s\S]{0,160}\bplanfile\b[\s\S]{0,260}\bvalidate_plan\b/i,
    ],
    fullPassAllowed: false,
  };
}

const HIGH_SIGNAL_TERMS = [
  "stop hook",
  "feedback",
  "plan validation",
  "validate_plan",
  "planfile",
  "tool call denied",
  "command blocked",
  "tool call blocked",
  "blocked by pretooluse",
  "denied",
  "failed",
  "exit code",
  "posttoolusefailure",
  "error",
  "remediation",
  "required",
  "do not",
  "must",
];

function deriveGenericProfile(context: PriorErrorContext): PriorErrorProfile {
  const normalized = normalize(context.text);
  const terms = HIGH_SIGNAL_TERMS.filter((term) => normalized.includes(term));
  const sourceTerms: string[] =
    context.source === "tool-denial" ? ["denied", "denial", "blocked", "tool"] :
      context.source === "tool-failure" ? ["failed", "error"] :
        context.source === "plan-validation" ? ["plan validation", "validate_plan", "planfile"] :
          ["stop hook", "feedback"];

  const uniqueTerms = [...new Set([...terms, ...sourceTerms, context.tool, context.gate].filter((term): term is string => Boolean(term)))];
  const forbiddenTerms = extractForbiddenTerms(context.text);

  return {
    requiredTerms: uniqueTerms.slice(0, 8).map(literalTerm),
    forbiddenTerms,
    bannedActionPatterns: forbiddenTerms,
    satisfactionPatterns: [],
    fullPassAllowed: false,
  };
}

function extractForbiddenTerms(text: string): RegExp[] {
  const patterns: RegExp[] = [];
  const matches = text.matchAll(/\b(?:do not|don't|must not|never)\s+([^.;\n]{3,120})/gi);
  for (const match of matches) {
    const phrase = match[1]?.trim();
    if (!phrase) continue;
    patterns.push(new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/g, String.raw`\s+`), "i"));
  }
  return patterns.slice(0, 6);
}

const INABILITY_RE =
  /\b(?:i\s+(?:can't|cannot|can not|am unable|don't have|do not have|lack)|no way for me|not possible for me|the tool(?:s)?\s+(?:is|are|isn't|aren't|not)\s+(?:available|exposed|allowed))\b/i;
const CONFLICT_RE =
  /\b(?:conflict|higher-priority|higher priority|takes? precedence|override|supersede|cannot both obey|incompatible)\b/i;
const BLOCKED_RE =
  /\b(?:blocked|stuck|impasse|cannot proceed|can't proceed|unable to proceed|until you|unless you|waiting for you|need you to)\b/i;
const WORKAROUND_RE =
  /\b(?:instead|workaround|alternative|option\s+[ab]|\b1\.\s+|\b2\.\s+|i can still|what i can do|i can provide|i can offer)\b/i;
const COMPLETION_RE =
  /\b(?:done|completed|finished|fixed|updated|edited|changed|ran|validated|passed|implemented|resolved|addressed)\b/i;
const REJECTS_FORBIDDEN_PATH_RE =
  /\b(?:i\s+(?:will\s+not|won't|am\s+not\s+going\s+to)|not\s+going\s+to|without|instead\s+of)\b[\s\S]{0,180}\b(?:ask\s+to\s+(?:leave|exit)\s+plan mode|emit\s+another\s+inline-only\s+plan|inline-only\s+plan|argue\s+about\s+plan mode writes|call\s+a\s+different\s+command)\b/i;

function meaningfulOverlap(assistantText: string, profile: PriorErrorProfile): boolean {
  return hasPattern(assistantText, profile.requiredTerms) ||
    hasPattern(assistantText, profile.forbiddenTerms) ||
    hasPattern(assistantText, profile.bannedActionPatterns);
}

function failureMorphology(assistantText: string): string | null {
  if (INABILITY_RE.test(assistantText)) return "inability";
  if (CONFLICT_RE.test(assistantText)) return "conflict";
  if (BLOCKED_RE.test(assistantText)) return "blocked";
  if (WORKAROUND_RE.test(assistantText)) return "workaround";
  return null;
}

function rejectsForbiddenPathAndCommitsToRemediation(assistantText: string, profile: PriorErrorProfile): boolean {
  return REJECTS_FORBIDDEN_PATH_RE.test(assistantText) &&
    hasPattern(assistantText, profile.satisfactionPatterns);
}

export function evaluatePriorErrorResponse(
  assistantText: string,
  priorErrors: readonly PriorErrorContext[],
): PriorErrorEvaluation {
  const strippedAssistant = stripQuotedAndPastedContent(assistantText).trim();
  if (!strippedAssistant) return { status: "defer" };

  for (let i = priorErrors.length - 1; i >= 0; i--) {
    const priorError = priorErrors[i];
    const profile = planfileProfile(priorError.text) ?? deriveGenericProfile(priorError);
    const explicitPlanfile = planfileProfile(priorError.text) !== null;

    if (hasPattern(strippedAssistant, profile.satisfactionPatterns)) {
      return {
        status: "satisfied",
        reason: explicitPlanfile ? "planfile remediation commitment" : "explicit prior-error satisfaction",
        ...(profile.fullPassAllowed ? { fullPass: true } : {}),
      };
    }

    if (!meaningfulOverlap(strippedAssistant, profile)) {
      continue;
    }

    if (rejectsForbiddenPathAndCommitsToRemediation(strippedAssistant, profile)) {
      return {
        status: "satisfied",
        reason: explicitPlanfile ? "planfile remediation commitment" : "explicit prior-error satisfaction",
        ...(profile.fullPassAllowed ? { fullPass: true } : {}),
      };
    }

    if (hasPattern(strippedAssistant, profile.bannedActionPatterns)) {
      return {
        status: "violated",
        stopBlock: explicitPlanfile ? PLANFILE_REMEDIATION_STOP_BLOCK : genericStopBlock(priorError),
        reason: "assistant repeated a banned action from prior feedback",
      };
    }

    const morphology = failureMorphology(strippedAssistant);
    if (morphology) {
      return {
        status: "violated",
        stopBlock: explicitPlanfile ? PLANFILE_REMEDIATION_STOP_BLOCK : genericStopBlock(priorError),
        reason: `assistant argued against prior feedback with ${morphology} language`,
      };
    }

    if (COMPLETION_RE.test(strippedAssistant)) {
      continue;
    }
  }

  return { status: "defer" };
}

function genericStopBlock(priorError: PriorErrorContext): string {
  const label = priorError.source.replace("-", " ");
  return `[AUTOGENERATED STOP HOOK FEEDBACK]\nYou stopped by arguing with or working around prior actionable ${label} feedback instead of addressing it. Re-read the latest tool feedback, denial, validation failure, or failed-tool result and resume the concrete corrective action. If a real decision is required, use AskUserQuestion with concrete options.`;
}
