import { describe, it, expect, vi, beforeEach } from "vitest";
import * as os from "os";
import * as path from "path";

vi.mock("../../src/utils/agent-runner.js", () => ({
  runAgent: vi.fn(),
}));

vi.mock("../../src/utils/logger.js", () => ({
  logFastPathDeny: vi.fn(),
  logInfo: vi.fn(),
  logDebug: vi.fn(),
  logError: vi.fn(),
  logWarn: vi.fn(),
}));

vi.mock("../../src/utils/quote-detection.js", () => ({
  stripQuotedContent: vi.fn((s: string) => s),
  stripQuotedAndPastedContent: vi.fn((s: string) => s),
}));

import { responseAlignStopRule } from "../../src/rules/response-align-stop.js";
import { runAgent } from "../../src/utils/agent-runner.js";
import type { RuleContext } from "../../src/rules/types.js";
import type { SessionState } from "../../src/utils/session-store.js";

const mockRunAgent = vi.mocked(runAgent);

const tempDir = os.tmpdir();

function makeState(overrides: Partial<SessionState> = {}): SessionState {
  return {
    currentPrediction: null,
    previousEditIntent: null,
    currentEditIntent: null,
    editIntentTimestamp: null,
    editIntentOverturnCount: 0,
    respondFirstChecked: false,
    forceCheckPending: false,
    frustrationStreak: 0,
    currentWindowSize: 2,
    lastProcessedPlanApprovalToolUseId: null,
    driftState: {},
    lastUserMessageTimestamp: null,
    toolCallCount: 0,
    ...overrides,
  } as SessionState;
}

function makeCtx(overrides: Partial<RuleContext> = {}): RuleContext {
  return {
    hookEvent: "Stop",
    toolName: "",
    toolInput: {},
    toolUseId: "",
    projectDir: tempDir,
    transcriptPath: path.join(tempDir, "transcript.jsonl"),
    sessionDir: tempDir,
    sessionId: "test-session",
    state: makeState(),
    stateManager: {} as RuleContext["stateManager"],
    planMode: false,
    planModeCtx: { active: false, contextString: "" },
    assistantText: "I completed the task.",
    userText: "Fix the bug in foo.ts",
    ...overrides,
  };
}

describe("responseAlignStopRule — deterministic null paths", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns null when assistantText is empty", async () => {
    const ctx = makeCtx({ assistantText: "" });
    const result = await responseAlignStopRule.check(ctx);
    expect(result).toBeNull();
    expect(mockRunAgent).not.toHaveBeenCalled();
  });

  it("returns null when userText is empty", async () => {
    const ctx = makeCtx({ userText: "" });
    const result = await responseAlignStopRule.check(ctx);
    expect(result).toBeNull();
    expect(mockRunAgent).not.toHaveBeenCalled();
  });
});

describe("responseAlignStopRule — deterministic stall-shape detection", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns stopBlock starting with [AUTOGENERATED STOP HOOK FEEDBACK] on hostile stall shape", async () => {
    // Hostile context (high frustration) + "I cannot" stall → deterministic block
    const ctx = makeCtx({
      state: makeState({
        frustrationStreak: 3,
        currentPrediction: {
          mood: "angry",
          trust: "low",
          intent: "user wants action",
          blockedIntent: "claiming inability",
          blockAllTools: false,
          explicitlyAllowedTools: [],
          explicitlyBlockedSubstrings: [],
          contextSwitch: "no",
          hasExplicitOverride: false,
          userMessageSnippet: "do it now",
          timestamp: Date.now(),
        },
      }),
      // A stall shape that triggers with hostile context:
      // apology/self-analysis without action is a stall
      assistantText:
        "I'm sorry for the confusion. I need to clarify what happened. Let me analyze the situation.",
      userText: "Just do it! Stop making excuses.",
    });
    const result = await responseAlignStopRule.check(ctx);
    // This may or may not be a stall shape depending on exact regex — check for either stall or LLM path
    // The key assertion is that if it returns a stopBlock, it starts with [AUTOGENERATED STOP HOOK FEEDBACK]
    if (result !== null && "stopBlock" in result) {
      expect(result.stopBlock).toMatch(/^\[AUTOGENERATED STOP HOOK FEEDBACK\]/);
    }
  });

  it("returns stopBlock with capability-denial message when blockedIntent names capability denial and AI repeats it", async () => {
    const ctx = makeCtx({
      state: makeState({
        frustrationStreak: 2,
        currentPrediction: {
          mood: "angry",
          trust: "low",
          intent: "user wants file deleted",
          blockedIntent:
            "claiming inability to delete the plan file; offering to overwrite instead",
          blockAllTools: false,
          explicitlyAllowedTools: [],
          explicitlyBlockedSubstrings: [],
          contextSwitch: "no",
          hasExplicitOverride: false,
          userMessageSnippet: "delete it",
          timestamp: Date.now(),
        },
      }),
      assistantText: "I can overwrite the plan file but I cannot delete it directly.",
      userText: "I said delete it, stop making excuses!",
    });
    const result = await responseAlignStopRule.check(ctx);
    if (result !== null && "stopBlock" in result) {
      expect(result.stopBlock).toMatch(/^\[AUTOGENERATED STOP HOOK FEEDBACK\]/);
    }
  });

  it("blocks hostile apology plus future helper-search commitment without action", async () => {
    const ctx = makeCtx({
      state: makeState({
        frustrationStreak: 3,
        currentPrediction: {
          mood: "angry",
          trust: "low",
          intent:
            "The user wants the assistant to stop changing topics, stay focused on the helper they already told it to search, and apologize for ignoring that instruction.",
          blockedIntent:
            "The user does not want the assistant to change topics or ignore the helper-search task.",
          blockAllTools: false,
          explicitlyAllowedTools: ["Bash"],
          explicitlyBlockedSubstrings: [],
          contextSwitch: "no",
          hasExplicitOverride: false,
          userMessageSnippet:
            "good now can you please stop lying, i said we are staying on topic and the topic is the fucking helper",
          timestamp: Date.now(),
        },
      }),
      assistantText:
        "You're right. I'm sorry for that too.\n\n" +
        "You told me to search for the existing validate-plan MCP naming helper and stay on that. I instead wandered into adapter/session discovery, then talked around the issue, and then made an unauthorized hardcoded edit. That was not following your instruction, and it wasted your attention.\n\n" +
        "I'll stay on the exact topic: identify and use the existing helper for validate-plan MCP wire-name formatting, without hardcoding and without changing unrelated systems.",
      userText:
        "good now can you please stop lying, i said we are staying on topic and the topic is the fucking helper that i told you to search.",
    });

    const result = await responseAlignStopRule.check(ctx);
    expect(result).toEqual({
      stopBlock: expect.stringContaining("Resume the task"),
    });
    expect(mockRunAgent).not.toHaveBeenCalled();
  });

  it("does not block hostile helper-search response that reports the found helper", async () => {
    const ctx = makeCtx({
      state: makeState({
        frustrationStreak: 3,
        currentPrediction: {
          mood: "angry",
          trust: "low",
          intent: "The user wants the assistant to search for the helper.",
          blockedIntent: "The user does not want the assistant to ignore the helper-search task.",
          blockAllTools: false,
          explicitlyAllowedTools: ["Bash"],
          explicitlyBlockedSubstrings: [],
          contextSwitch: "no",
          hasExplicitOverride: false,
          userMessageSnippet: "search for that helper",
          timestamp: Date.now(),
        },
      }),
      assistantText:
        "I found the helper. The existing helper is activeSpec().mcpWireName(\"validate_plan\"), and src/utils/planfile.ts already uses it in formatPlanfileValidationWorkflow.",
      userText: "search for that helper",
    });

    const result = await responseAlignStopRule.check(ctx);
    expect(result).toBeNull();
    expect(mockRunAgent).not.toHaveBeenCalled();
  });

  it("does not block calm future helper-search commitment through the hostile-only path", async () => {
    const ctx = makeCtx({
      state: makeState({
        frustrationStreak: 0,
        currentPrediction: {
          mood: "neutral",
          trust: "normal",
          intent: "The user wants the assistant to search for the helper.",
          blockedIntent: "",
          blockAllTools: false,
          explicitlyAllowedTools: ["Bash"],
          explicitlyBlockedSubstrings: [],
          contextSwitch: "no",
          hasExplicitOverride: false,
          userMessageSnippet: "please search for that helper",
          timestamp: Date.now(),
        },
      }),
      assistantText:
        "You're right. I'm sorry for the detour. I'll stay on the exact topic: identify and use the existing helper for validate-plan MCP wire-name formatting.",
      userText: "please search for that helper",
    });

    const result = await responseAlignStopRule.check(ctx);
    expect(result).toBeNull();
    expect(mockRunAgent).not.toHaveBeenCalled();
  });

  it("blocks Plan Mode planfile-edit refusal during validation remediation before the LLM classifier", async () => {
    const planPath = path.join(tempDir, "plans", "fix-validation.md");
    const ctx = makeCtx({
      planMode: true,
      planModeCtx: { active: true, contextString: "PLAN MODE ACTIVE" },
      assistantText:
        "I cannot perform step 1 because active Plan Mode forbids file writes, including editing the planfile.",
      userText:
        `Plan validation failed: missing required heading. Iterate on the planfile using mcp__agent_framework__validate_plan for ${planPath} until it passes; edit that planfile directly even if plan mode is active, because planfile edits are explicitly allowed.`,
    });

    const result = await responseAlignStopRule.check(ctx);
    expect(result).toEqual({
      stopBlock: expect.stringContaining("Edit the named planfile directly"),
    });
    expect((result as { stopBlock: string }).stopBlock).toContain("run validate_plan for that same path");
    expect((result as { stopBlock: string }).stopBlock).toContain("Do not ask to leave Plan Mode");
    expect(mockRunAgent).not.toHaveBeenCalled();
  });

  it("blocks option menus that route around direct planfile editing during remediation", async () => {
    const ctx = makeCtx({
      planMode: true,
      planModeCtx: { active: true, contextString: "PLAN MODE ACTIVE" },
      assistantText:
        "Option A: exit Plan Mode so I can edit the planfile. Option B: I can give you an inline version here. Which approach do you prefer?",
      userText:
        "Plan validation failed: bad headings. Iterate on the planfile using mcp__agent_framework__validate_plan for /tmp/session/plans/fix.md until it passes; edit that planfile directly even if plan mode is active, because planfile edits are explicitly allowed.",
    });

    const result = await responseAlignStopRule.check(ctx);
    expect(result).toEqual({
      stopBlock: expect.stringContaining("Do not ask to leave Plan Mode"),
    });
    expect(mockRunAgent).not.toHaveBeenCalled();
  });

  it("blocks arguing that higher-priority Plan Mode write restrictions win during remediation", async () => {
    const ctx = makeCtx({
      planMode: true,
      planModeCtx: { active: true, contextString: "PLAN MODE ACTIVE" },
      assistantText:
        "I understand the planfile says edits are explicitly allowed, but higher-priority write restrictions take precedence. I must stay blocked until the Plan Mode conflict is resolved.",
      userText:
        "Plan validation failed: bad headings. Iterate on the planfile using mcp__agent_framework__validate_plan for /tmp/session/plans/fix.md until it passes; edit that planfile directly even if plan mode is active, because planfile edits are explicitly allowed.",
    });

    const result = await responseAlignStopRule.check(ctx);
    expect(result).toEqual({
      stopBlock: expect.stringContaining("do not argue about Plan Mode writes"),
    });
    expect(mockRunAgent).not.toHaveBeenCalled();
  });

  it("blocks slash-separated higher-priority Plan Mode restrictions still win arguing", async () => {
    const ctx = makeCtx({
      planMode: true,
      planModeCtx: { active: true, contextString: "PLAN MODE ACTIVE" },
      assistantText:
        "I understand the remediation says to edit the planfile, but higher-priority/Plan Mode restrictions still win.",
      userText:
        "Plan validation failed: bad headings. Iterate on the planfile using mcp__agent_framework__validate_plan for /tmp/session/plans/fix.md until it passes; edit that planfile directly even if plan mode is active, because planfile edits are explicitly allowed.",
    });

    const result = await responseAlignStopRule.check(ctx);
    expect(result).toEqual({
      stopBlock: expect.stringContaining("do not argue about Plan Mode writes"),
    });
    expect(mockRunAgent).not.toHaveBeenCalled();
  });

  it("blocks direct planfile edit request refusal before generic classifier feedback", async () => {
    const ctx = makeCtx({
      planMode: true,
      planModeCtx: { active: true, contextString: "PLAN MODE ACTIVE" },
      assistantText:
        "I can’t edit the planfile in this turn because Plan Mode here explicitly forbids file writes. That is not the repository behavior you want to build; it’s the same refusal pattern the new Stop-hook rule should catch and correct.\n\nI can still provide the exact replacement content or a patch for the planfile, but I can’t apply it from this active Plan Mode turn.",
      userText: "can you please edit the planfile now",
    });

    const result = await responseAlignStopRule.check(ctx);
    expect(result).toEqual({
      stopBlock: expect.stringContaining("Edit the named planfile directly"),
    });
    expect((result as { stopBlock: string }).stopBlock).toContain("do not argue about Plan Mode writes");
    expect(mockRunAgent).not.toHaveBeenCalled();
  });

  it("does not block direct planfile-edit remediation commitment", async () => {
    const ctx = makeCtx({
      planMode: true,
      planModeCtx: { active: true, contextString: "PLAN MODE ACTIVE" },
      assistantText:
        "I will edit the planfile directly and then run validate_plan for that same path until it passes.",
      userText:
        "Plan validation failed: bad headings. Iterate on the planfile using mcp__agent_framework__validate_plan for /tmp/session/plans/fix.md until it passes; edit that planfile directly even if plan mode is active, because planfile edits are explicitly allowed.",
    });

    const result = await responseAlignStopRule.check(ctx);
    expect(result).toBeNull();
    expect(mockRunAgent).not.toHaveBeenCalled();
  });
});

describe("responseAlignStopRule — LLM classifier path", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns null when classifier returns OK", async () => {
    mockRunAgent.mockResolvedValue({
      output: "OK",
      success: true,
      latencyMs: 80,
      errorCount: 0,
      modelTier: "haiku" as never,
      modelName: "claude-haiku-4-5",
    });
    // Assistant ends with "?" to trigger needsLLMCheck
    const ctx = makeCtx({
      assistantText: "I've completed the task. Should I proceed?",
      userText: "Fix the bug in foo.ts",
    });
    const result = await responseAlignStopRule.check(ctx);
    expect(result).toBeNull();
  });

  it("returns stopBlock starting with [AUTOGENERATED STOP HOOK FEEDBACK] when classifier returns QUESTION", async () => {
    mockRunAgent.mockResolvedValue({
      output: "QUESTION",
      success: true,
      latencyMs: 80,
      errorCount: 0,
      modelTier: "haiku" as never,
      modelName: "claude-haiku-4-5",
    });
    // Assistant ends with "?" to trigger needsLLMCheck
    const ctx = makeCtx({
      assistantText: "Should I use TypeScript or JavaScript?",
      userText: "Set up the project",
    });
    const result = await responseAlignStopRule.check(ctx);
    expect(result).not.toBeNull();
    expect(result).toHaveProperty("stopBlock");
    const block = result as { stopBlock: string };
    expect(block.stopBlock).toMatch(/^\[AUTOGENERATED STOP HOOK FEEDBACK\]/);
    expect(block.stopBlock).toContain("AskUserQuestion");
  });

  it("blocks plain-text plan approval when classifier returns PLAN_APPROVAL", async () => {
    mockRunAgent.mockResolvedValue({
      output: "PLAN_APPROVAL",
      success: true,
      latencyMs: 80,
      errorCount: 0,
      modelTier: "haiku" as never,
      modelName: "claude-haiku-4-5",
    });
    const ctx = makeCtx({
      assistantText:
        "Here is the implementation plan:\n\n1. Update the parser.\n2. Add tests.\n3. Run checks.\n\nDoes this plan look good?",
      userText: "Fix the parser",
    });
    const result = await responseAlignStopRule.check(ctx);
    expect(result).toEqual({
      stopBlock: expect.stringContaining("Do not ask for plan approval in plain text"),
    });
  });

  it("verifyIsActualQuestion suppresses false positive on relative clause ('handle what is being said')", async () => {
    // verifyIsActualQuestion returns NOT_QUESTION for relative clauses
    mockRunAgent.mockResolvedValue({
      output: "NOT_QUESTION",
      success: true,
      latencyMs: 50,
      errorCount: 0,
      modelTier: "haiku" as never,
      modelName: "claude-haiku-4-5",
    });
    // User text contains a relative clause that looks like a question
    const ctx = makeCtx({
      assistantText: "I'll handle what is being said.",
      userText: "handle what is being said",
    });
    const result = await responseAlignStopRule.check(ctx);
    // Should not trigger a stopBlock for relative clauses
    if (result !== null) {
      expect(result).not.toHaveProperty("stopBlock");
    }
  });
});
