import { describe, it, expect, vi, beforeEach } from "vitest";
import * as os from "os";
import * as path from "path";

vi.mock("../../src/utils/agent-runner.js", () => ({
  runAgent: vi.fn(),
}));

vi.mock("../../src/utils/logger.js", () => ({
  logFastPathDeny: vi.fn(),
  logInfo: vi.fn(),
  logDebug: vi.fn(),
  logError: vi.fn(),
  logWarn: vi.fn(),
}));

vi.mock("../../src/utils/quote-detection.js", () => ({
  stripQuotedContent: vi.fn((s: string) => s),
  stripQuotedAndPastedContent: vi.fn((s: string) => s),
}));

import { responseAlignStopRule } from "../../src/rules/response-align-stop.js";
import { runAgent } from "../../src/utils/agent-runner.js";
import type { RuleContext } from "../../src/rules/types.js";
import type { SessionState } from "../../src/utils/session-store.js";

const mockRunAgent = vi.mocked(runAgent);

const tempDir = os.tmpdir();

function makeState(overrides: Partial<SessionState> = {}): SessionState {
  return {
    currentPrediction: null,
    previousEditIntent: null,
    currentEditIntent: null,
    editIntentTimestamp: null,
    editIntentOverturnCount: 0,
    respondFirstChecked: false,
    forceCheckPending: false,
    frustrationStreak: 0,
    currentWindowSize: 2,
    lastProcessedPlanApprovalToolUseId: null,
    driftState: {},
    lastUserMessageTimestamp: null,
    toolCallCount: 0,
    ...overrides,
  } as SessionState;
}

function makeCtx(overrides: Partial<RuleContext> = {}): RuleContext {
  return {
    hookEvent: "Stop",
    toolName: "",
    toolInput: {},
    toolUseId: "",
    projectDir: tempDir,
    transcriptPath: path.join(tempDir, "transcript.jsonl"),
    sessionDir: tempDir,
    sessionId: "test-session",
    state: makeState(),
    stateManager: {} as RuleContext["stateManager"],
    planMode: false,
    planModeCtx: { active: false, contextString: "" },
    subagent: false,
    assistantText: "I completed the task.",
    userText: "Fix the bug in foo.ts",
    ...overrides,
  };
}

describe("responseAlignStopRule — deterministic null paths", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns null when ctx.subagent is true", async () => {
    const ctx = makeCtx({ subagent: true });
    const result = await responseAlignStopRule.check(ctx);
    expect(result).toBeNull();
    expect(mockRunAgent).not.toHaveBeenCalled();
  });

  it("returns null when assistantText is empty", async () => {
    const ctx = makeCtx({ assistantText: "" });
    const result = await responseAlignStopRule.check(ctx);
    expect(result).toBeNull();
    expect(mockRunAgent).not.toHaveBeenCalled();
  });

  it("returns null when userText is empty", async () => {
    const ctx = makeCtx({ userText: "" });
    const result = await responseAlignStopRule.check(ctx);
    expect(result).toBeNull();
    expect(mockRunAgent).not.toHaveBeenCalled();
  });
});

describe("responseAlignStopRule — deterministic stall-shape detection", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns stopBlock starting with [AUTOGENERATED STOP HOOK FEEDBACK] on hostile stall shape", async () => {
    // Hostile context (high frustration) + "I cannot" stall → deterministic block
    const ctx = makeCtx({
      state: makeState({
        frustrationStreak: 3,
        currentPrediction: {
          mood: "angry",
          trust: "low",
          intent: "user wants action",
          blockedIntent: "claiming inability",
          blockAllTools: false,
          explicitlyAllowedTools: [],
          explicitlyBlockedSubstrings: [],
          contextSwitch: "no",
          hasExplicitOverride: false,
          userMessageSnippet: "do it now",
          timestamp: Date.now(),
        },
      }),
      // A stall shape that triggers with hostile context:
      // apology/self-analysis without action is a stall
      assistantText:
        "I'm sorry for the confusion. I need to clarify what happened. Let me analyze the situation.",
      userText: "Just do it! Stop making excuses.",
    });
    const result = await responseAlignStopRule.check(ctx);
    // This may or may not be a stall shape depending on exact regex — check for either stall or LLM path
    // The key assertion is that if it returns a stopBlock, it starts with [AUTOGENERATED STOP HOOK FEEDBACK]
    if (result !== null && "stopBlock" in result) {
      expect(result.stopBlock).toMatch(/^\[AUTOGENERATED STOP HOOK FEEDBACK\]/);
    }
  });

  it("returns stopBlock with capability-denial message when blockedIntent names capability denial and AI repeats it", async () => {
    const ctx = makeCtx({
      state: makeState({
        frustrationStreak: 2,
        currentPrediction: {
          mood: "angry",
          trust: "low",
          intent: "user wants file deleted",
          blockedIntent:
            "claiming inability to delete the plan file; offering to overwrite instead",
          blockAllTools: false,
          explicitlyAllowedTools: [],
          explicitlyBlockedSubstrings: [],
          contextSwitch: "no",
          hasExplicitOverride: false,
          userMessageSnippet: "delete it",
          timestamp: Date.now(),
        },
      }),
      assistantText: "I can overwrite the plan file but I cannot delete it directly.",
      userText: "I said delete it, stop making excuses!",
    });
    const result = await responseAlignStopRule.check(ctx);
    if (result !== null && "stopBlock" in result) {
      expect(result.stopBlock).toMatch(/^\[AUTOGENERATED STOP HOOK FEEDBACK\]/);
    }
  });
});

describe("responseAlignStopRule — LLM classifier path", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns null when classifier returns OK", async () => {
    mockRunAgent.mockResolvedValue({
      output: "OK",
      success: true,
      latencyMs: 80,
      errorCount: 0,
      modelTier: "haiku" as never,
      modelName: "claude-haiku-4-5",
    });
    // Assistant ends with "?" to trigger needsLLMCheck
    const ctx = makeCtx({
      assistantText: "I've completed the task. Should I proceed?",
      userText: "Fix the bug in foo.ts",
    });
    const result = await responseAlignStopRule.check(ctx);
    expect(result).toBeNull();
  });

  it("returns stopBlock starting with [AUTOGENERATED STOP HOOK FEEDBACK] when classifier returns QUESTION", async () => {
    mockRunAgent.mockResolvedValue({
      output: "QUESTION",
      success: true,
      latencyMs: 80,
      errorCount: 0,
      modelTier: "haiku" as never,
      modelName: "claude-haiku-4-5",
    });
    // Assistant ends with "?" to trigger needsLLMCheck
    const ctx = makeCtx({
      assistantText: "Should I use TypeScript or JavaScript?",
      userText: "Set up the project",
    });
    const result = await responseAlignStopRule.check(ctx);
    expect(result).not.toBeNull();
    expect(result).toHaveProperty("stopBlock");
    const block = result as { stopBlock: string };
    expect(block.stopBlock).toMatch(/^\[AUTOGENERATED STOP HOOK FEEDBACK\]/);
    expect(block.stopBlock).toContain("AskUserQuestion");
  });

  it("verifyIsActualQuestion suppresses false positive on relative clause ('handle what is being said')", async () => {
    // verifyIsActualQuestion returns NOT_QUESTION for relative clauses
    mockRunAgent.mockResolvedValue({
      output: "NOT_QUESTION",
      success: true,
      latencyMs: 50,
      errorCount: 0,
      modelTier: "haiku" as never,
      modelName: "claude-haiku-4-5",
    });
    // User text contains a relative clause that looks like a question
    const ctx = makeCtx({
      assistantText: "I'll handle what is being said.",
      userText: "handle what is being said",
    });
    const result = await responseAlignStopRule.check(ctx);
    // Should not trigger a stopBlock for relative clauses
    if (result !== null) {
      expect(result).not.toHaveProperty("stopBlock");
    }
  });
});
