import { execSync } from "child_process";
import { getModelId } from "../../types.js";
import { logToHomeAssistant } from "../../utils/logger.js";
import { runAgentQuery } from "../../utils/agent-query.js";
import { runConfirmAgent } from "./confirm.js";

export async function runCommitAgent(workingDir: string): Promise<string> {
  // Pre-check: skip LLM call if nothing to commit
  const status = execSync("git status --porcelain", { cwd: workingDir, encoding: "utf-8" });
  if (!status.trim()) {
    logToHomeAssistant({
      agent: 'commit',
      level: 'info',
      problem: workingDir,
      answer: 'SKIPPED: nothing to commit',
    });
    return "SKIPPED: nothing to commit";
  }

  // Confirm changes before generating commit message
  const confirmResult = await runConfirmAgent(workingDir);
  if (confirmResult.startsWith("DECLINED")) {
    logToHomeAssistant({
      agent: 'commit',
      level: 'info',
      problem: workingDir,
      answer: confirmResult,
    });
    return confirmResult;
  }

  const result = await runAgentQuery(
    'commit',
    `1. Run \`git diff --stat HEAD\` to count files and lines changed
2. Classify the change size based on stats
3. Run \`git diff HEAD\` to understand the actual changes
4. Generate commit message matching the classified size
5. Execute \`git add -A && git commit -m "..."\`
6. Return SIZE, the commit message, and HASH`,
    {
      cwd: workingDir,
      model: getModelId("sonnet"),
      allowedTools: ["Bash"],
      systemPrompt: `You are a commit message generator. Follow this EXACT process.

STEP 1: CLASSIFY CHANGE SIZE
Run \`git diff --stat HEAD\` and classify based on the summary line:
- SMALL: 1-3 files AND <50 lines total changed
- MEDIUM: 4-10 files OR 50-200 lines total changed
- LARGE: 10+ files OR 200+ lines total changed

STEP 2: GENERATE MESSAGE MATCHING SIZE
You MUST use the format for your classified size:

SMALL format - single lowercase line, no period:
  fix typo in readme
  add null check
  update dependency version

MEDIUM format - single line with scope prefix:
  auth: add jwt refresh token handling
  api: handle rate limit responses
  db: add user preferences migration

LARGE format - title line + blank line + bullet points:
  refactor: restructure module architecture

  - Extract validators to dedicated directory
  - Add comprehensive unit tests
  - Update imports across codebase
  - Remove deprecated utilities

STEP 3: COMMIT
Run \`git add -A && git commit -m "..."\`

RULES:
- NEVER use vague words: "various", "updates", "changes", "improvements", "misc"
- NEVER list file names in the message unless critical to understanding
- NEVER push (commit only)
- NEVER use emojis
- NEVER add credits, co-authors, or "generated by" lines
- For LARGE: bullets MUST describe what changed conceptually, NOT list files
- For LARGE: 3-6 bullet points summarizing the key changes

===== OUTPUT FORMAT (STRICT) =====
After committing, output EXACTLY this format:

SIZE: <SMALL|MEDIUM|LARGE>
<full commit message exactly as committed>
HASH: <commit hash>

Example SMALL:
SIZE: SMALL
fix null pointer in auth handler
HASH: abc123def

Example MEDIUM:
SIZE: MEDIUM
api: add retry logic for failed requests
HASH: abc123def

Example LARGE:
SIZE: LARGE
refactor: restructure agents directory

- Move MCP agents to dedicated subdirectory
- Consolidate hook agents under hooks/
- Update documentation and imports
- Remove deprecated utility functions
HASH: abc123def`
    }
  );

  logToHomeAssistant({
    agent: 'commit',
    level: 'info',
    problem: workingDir,
    answer: result.output,
  });

  return result.output;
}
