import { getModelId } from "../../types.js";
import { getAnthropicClient } from "../../utils/anthropic-client.js";
import { runCommand } from "../../utils/command.js";
import { logToHomeAssistant } from "../../utils/logger.js";
import { extractTextFromResponse } from "../../utils/response-parser.js";
import { runConfirmAgent } from "./confirm.js";

const SYSTEM_PROMPT = `You are a commit message generator. Generate a commit message based on the provided analysis and diff stats.

STEP 1: CLASSIFY CHANGE SIZE
Based on the diff stats provided:
- SMALL: 1-3 files AND <50 lines total changed
- MEDIUM: 4-10 files OR 50-200 lines total changed
- LARGE: 10+ files OR 200+ lines total changed

STEP 2: GENERATE MESSAGE MATCHING SIZE
You MUST use the format for your classified size:

SMALL format - single lowercase line, no period:
  fix typo in readme
  add null check
  update dependency version

MEDIUM format - single line with scope prefix:
  auth: add jwt refresh token handling
  api: handle rate limit responses
  db: add user preferences migration

LARGE format - title line + blank line + bullet points:
  refactor: restructure module architecture

  - Extract validators to dedicated directory
  - Add comprehensive unit tests
  - Update imports across codebase
  - Remove deprecated utilities

RULES:
- NEVER use vague words: "various", "updates", "changes", "improvements", "misc"
- NEVER list file names in the message unless critical to understanding
- NEVER use emojis
- NEVER add credits, co-authors, or "generated by" lines
- For LARGE: bullets MUST describe what changed conceptually, NOT list files
- For LARGE: 3-6 bullet points summarizing the key changes

===== OUTPUT FORMAT (STRICT) =====
Output EXACTLY this format:

SIZE: <SMALL|MEDIUM|LARGE>
MESSAGE:
<full commit message>

Example SMALL:
SIZE: SMALL
MESSAGE:
fix null pointer in auth handler

Example MEDIUM:
SIZE: MEDIUM
MESSAGE:
api: add retry logic for failed requests

Example LARGE:
SIZE: LARGE
MESSAGE:
refactor: restructure agents directory

- Move MCP agents to dedicated subdirectory
- Consolidate hook agents under hooks/
- Update documentation and imports
- Remove deprecated utility functions`;

/**
 * Parse the LLM response to extract size and message.
 */
function parseCommitResponse(response: string): { size: string; message: string } | null {
  const sizeMatch = response.match(/SIZE:\s*(SMALL|MEDIUM|LARGE)/i);
  const messageMatch = response.match(/MESSAGE:\s*\n([\s\S]+?)(?:\n\n|$)/);

  if (!sizeMatch) return null;

  const size = sizeMatch[1].toUpperCase();
  const message = messageMatch ? messageMatch[1].trim() : response.split("MESSAGE:")[1]?.trim() || "";

  return { size, message };
}

export async function runCommitAgent(workingDir: string): Promise<string> {
  // Pre-check: skip LLM call if nothing to commit
  const status = runCommand("git status --porcelain", workingDir);
  if (!status.output.trim()) {
    logToHomeAssistant({
      agent: "commit",
      level: "info",
      problem: workingDir,
      answer: "SKIPPED: nothing to commit",
    });
    return "SKIPPED: nothing to commit";
  }

  // Confirm changes before generating commit message
  const confirmResult = await runConfirmAgent(workingDir);
  if (confirmResult.startsWith("DECLINED")) {
    logToHomeAssistant({
      agent: "commit",
      level: "info",
      problem: workingDir,
      answer: confirmResult,
    });
    return confirmResult;
  }

  // Get diff stats for size classification
  const diffStat = runCommand("git diff --stat HEAD", workingDir);
  const diff = runCommand("git diff HEAD", workingDir);

  // Single API call to generate commit message
  const client = getAnthropicClient();
  const response = await client.messages.create({
    model: getModelId("haiku"),
    max_tokens: 1000,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: `CONFIRM AGENT ANALYSIS:
${confirmResult}

---

DIFF STATS:
${diffStat.output}

DIFF (for context):
${diff.output.slice(0, 8000)}${diff.output.length > 8000 ? "\n... (truncated)" : ""}

Generate a commit message based on the analysis and stats above.`,
      },
    ],
  });

  const llmOutput = extractTextFromResponse(response);
  const parsed = parseCommitResponse(llmOutput);

  if (!parsed || !parsed.message) {
    const error = `ERROR: Failed to parse commit message from LLM response: ${llmOutput}`;
    logToHomeAssistant({
      agent: "commit",
      level: "error",
      problem: workingDir,
      answer: error,
    });
    return error;
  }

  // Execute the commit
  const commitCmd = `git add -A && git commit -m ${JSON.stringify(parsed.message)}`;
  const commit = runCommand(commitCmd, workingDir);

  if (commit.exitCode !== 0) {
    const error = `ERROR: Commit failed: ${commit.output}`;
    logToHomeAssistant({
      agent: "commit",
      level: "error",
      problem: workingDir,
      answer: error,
    });
    return error;
  }

  // Extract commit hash
  const hashResult = runCommand("git rev-parse --short HEAD", workingDir);
  const hash = hashResult.output.trim();

  const output = `${confirmResult}\n\nSIZE: ${parsed.size}\n${parsed.message}\nHASH: ${hash}`;

  logToHomeAssistant({
    agent: "commit",
    level: "info",
    problem: workingDir,
    answer: output,
  });

  return output;
}
