export const READ_ONLY_GIT_COMMAND_CASES = [
  "git status --short",
  "git --git-dir=.git status --short",
  "git --git-dir .git status --short",
  "git --work-tree /tmp status --short",
  "git diff -- src/index.ts",
  "git log --oneline -10",
  "git show HEAD:package.json",
  "git branch",
  "git branch --show-current",
  "git branch --contains HEAD",
  "git branch -a",
  "git branch --all",
  "git branch -r",
  "git -C submodule/path submodule status",
  "git submodule summary",
  "git remote -v",
  "git remote get-url origin",
  "git remote show -n origin",
  "git worktree list",
  "git tag",
  "git tag --list v*",
  "git reflog show --date=iso",
  "git stash list",
  "git stash show stash@{0}",
  "git config --get remote.origin.url",
  "git config --file .git/config --get user.name",
  "git config --file .git/config --list --show-origin",
  "git config --get-regexp foo bar",
  "git config --get-urlmatch foo bar",
  "git ls-tree HEAD src",
] as const;

export const MUTATING_GIT_COMMAND_CASES = [
  "git add .",
  "git -C repo add .",
  "git fetch origin",
  "git --git-dir=.git push",
  "git --git-dir .git push",
  "git --work-tree /tmp push",
  "git -C repo push",
  "git -C repo commit -m fix",
  "sudo git push",
  "sudo -n git push",
  "sudo -p prompt git push",
  "sudo -u root git push",
  "time git commit -m fix",
  "time -p git commit -m fix",
  "env GIT_DIR=.git git push",
  "exec git push",
  "exec -a name git push",
  "command -p git push",
  "nohup git push",
  "( git push )",
  "(git push)",
  "(git commit -m fix)",
  "(git branch -d old-topic)",
  "if git push; then echo ok; fi",
  "if true; then git push; fi",
  "while git push; do :; done",
  "! git push",
  "until git push; do :; done",
  "eval git push",
  "eval \"git push\"",
  "nice git push",
  "nice -n 10 git push",
  "stdbuf -oL git commit -m fix",
  "timeout 5 git push",
  "timeout -k 1s 5s git push",
  "setsid git push",
  "timeout sh -c 'git push'",
  "sudo sh -c 'git push'",
  "env sh -c 'git push'",
  "dash -c 'git push'",
  "busybox sh -c 'git push'",
  "parallel git push",
  "watch git push",
  "sh -c 'git push'",
  "bash -lc 'git push'",
  "case x in x) git push ;; esac",
  "git -C \"repo path\" push",
  "git -c \"safe.directory=*\" push",
  "env -u FOO git push",
  "env -i git push",
  "env -C /tmp git push",
  "env --chdir=/tmp git push",
  "git submodule update --init --recursive",
  "git branch -d old-topic",
  "git branch new-topic",
  "git branch -uorigin/main",
  "git branch -rd origin/foo",
  "git branch -rD origin/foo",
  "git branch --track foo",
  "git branch --create-reflog foo",
  "git tag v1.2.3",
  "git tag -- -x",
  "git tag -d v1.2.3",
  "git remote add origin https://example.invalid/repo.git",
  "git remote show origin",
  "git stash",
  "git stash push -m work",
  "git worktree add ../copy HEAD",
  "git reflog expire --expire=now --all",
  "git config user.name Tim",
  "git config edit",
  "git config --global edit",
  "git config set user.name Tim",
] as const;
